package com.bizoffs.order.pojo;

import lombok.Data;

import java.io.Serializable;
import java.sql.Timestamp;

;

@Data
public class PartyPojo implements Serializable {
    private static final long serialVersionUID = 1L;
    private String partyId;
    private Timestamp createdDate;
    private Timestamp createdStamp;
    private Timestamp createdTxStamp;
    private String description;
    private String externalId;
    private String isUnread;
    private Timestamp lastModifiedDate;
    private Timestamp lastUpdatedStamp;
    private Timestamp lastUpdatedTxStamp;
 /*   private List<AcctgTran> acctgTrans;
    private List<AcctgTransEntry> acctgTransEntries;
    private Affiliate affiliate;
    private List<AgreementPartyApplic> agreementPartyApplics;
    private List<AgreementRole> agreementRoles;
    private List<BillingAccountRole> billingAccountRoles;
    private List<BudgetReview> budgetReviews;
    private List<BudgetRole> budgetRoles;
    private List<CarrierShipmentBoxType> carrierShipmentBoxTypes;
    private List<CarrierShipmentMethod> carrierShipmentMethods;
    private List<CommunicationEvent> communicationEvents1;

    private List<CommunicationEventRole> communicationEventRoles;
    private List<ContactList> contactLists;
    private List<ContactListCommStatus> contactListCommStatuses;
    private List<ContactListParty> contactListParties;
    private List<ContentApproval> contentApprovals;
    private List<ContentRevision> contentRevisions;
    private List<CostComponent> costComponents;
    private List<CustomTimePeriod> customTimePeriods;
    private List<CustRequest> custRequests;
    private List<CustRequestParty> custRequestParties;
    private List<CustRequestType> custRequestTypes;
    private List<Employment> employments1;

    private List<EmploymentApp> employmentApps;
    private List<EmplLeave> emplLeaves1;

    private List<EmplPosition> emplPositions;
    private List<EmplPositionFulfillment> emplPositionFulfillments;
    private List<Facility> facilities;
    private List<FacilityCarrierShipment> facilityCarrierShipments;
    private List<FacilityParty> facilityParties;
    private List<FinAccount> finAccounts1;

    private List<FinAccountTran> finAccountTrans1;

    private List<FinAccountTypeGlAccount> finAccountTypeGlAccounts;
    private List<FixedAsset> fixedAssets;
    private List<FixedAssetRegistration> fixedAssetRegistrations;
    private List<FixedAssetTypeGlAccount> fixedAssetTypeGlAccounts;
    private List<GiftCardFulfillment> giftCardFulfillments;
    private List<GlAccountHistory> glAccountHistories;
    private List<GlAccountOrganization> glAccountOrganizations;
    private List<GlAccountTypeDefault> glAccountTypeDefaults;
    private List<GlJournal> glJournals;
    private List<GlReconciliation> glReconciliations;
    private List<InventoryItem> inventoryItems1;
    private List<InventoryItem> inventoryItems2;
    private List<Invoice> invoices1;
    private List<Invoice> invoices2;
    private List<InvoiceItem> invoiceItems1;
    private List<InvoiceItem> invoiceItems2;
    private List<InvoiceItemTypeGlAccount> invoiceItemTypeGlAccounts;
    private List<InvoiceRole> invoiceRoles;
    private List<ItemIssuanceRole> itemIssuanceRoles;
    private List<JobInterview> jobInterviews1;
    private List<JobInterview> jobInterviews2;
    private List<NoteData> noteData;
    private List<OrderItemRole> orderItemRoles;
    private List<OrderItemShipGroup> orderItemShipGroups1;
    private List<OrderItemShipGroup> orderItemShipGroups2;
    private List<OrderItemShipGroup> orderItemShipGroups3;
    private List<OrderRole> orderRoles;
    private DataSource dataSource;
    private PartyType partyType;
    private StatusItem statusItem;
    private Uom uom;
    private UserLogin userLogin1;
    private UserLogin userLogin2;
    private PartyAcctgPreference partyAcctgPreference;
    private List<PartyAttribute> partyAttributes;
    private List<PartyBenefit> partyBenefits1;
    private List<PartyBenefit> partyBenefits2;
    private List<PartyCarrierAccount> partyCarrierAccounts1;
    private List<PartyCarrierAccount> partyCarrierAccounts2;
    private List<PartyClassification> partyClassifications;
    private List<PartyContactMech> partyContactMeches;
    private List<PartyContactMechPurpose> partyContactMechPurposes;
    private List<PartyContent> partyContents;
    private List<PartyDataSource> partyDataSources;
    private List<PartyGeoPoint> partyGeoPoints;
    private List<PartyGlAccount> partyGlAccounts1;
    private List<PartyGlAccount> partyGlAccounts2;
    private PartyGroup partyGroup;
    private PartyIcsAvsOverride partyIcsAvsOverride;
    private List<PartyIdentification> partyIdentifications;
    private List<PartyInvitation> partyInvitations;
    private List<PartyInvitationGroupAssoc> partyInvitationGroupAssocs;
    private List<PartyNameHistory> partyNameHistories;
    private List<PartyNeed> partyNeeds;
    private List<PartyNote> partyNotes;
    private List<PartyPrefDocTypeTpl> partyPrefDocTypeTpls;
    private List<PartyProfileDefault> partyProfileDefaults;
    private List<PartyQual> partyQuals;
    private List<PartyRateNew> partyRateNews;
    private List<PartyResume> partyResumes;
    private List<PartyRole> partyRoles;
    private List<PartySkill> partySkills;
    private List<PartyStatus> partyStatuses;
    private List<PartyTaxAuthInfo> partyTaxAuthInfos;
    private List<Payment> payments1;
    private List<Payment> payments2;
    private List<PaymentGlAccountTypeMap> paymentGlAccountTypeMaps;
    private List<PaymentMethod> paymentMethods;
    private List<PaymentMethodTypeGlAccount> paymentMethodTypeGlAccounts;
    private List<PayrollPreference> payrollPreferences;
    private List<PerformanceNote> performanceNotes;
    private List<PerfReview> perfReviews1;
    private List<PerfReview> perfReviews2;
    private List<PerfReviewItem> perfReviewItems;
    private PersonPojo person;
    private List<PersonTraining> personTrainings;
    private List<ProductAverageCost> productAverageCosts;
    private List<ProductCategoryGlAccount> productCategoryGlAccounts;
    private List<ProductGlAccount> productGlAccounts;
    private List<ProductPrice> productPrices;
    private List<ProductPromo> productPromos;
    private List<ProductPromoCodeParty> productPromoCodeParties;
    private List<ProductPromoUse> productPromoUses;
    private List<ProductStore> productStores;
    private List<ProductStoreVendorPayment> productStoreVendorPayments;
    private List<ProductStoreVendorShipment> productStoreVendorShipments1;
    private List<ProductStoreVendorShipment> productStoreVendorShipments2;
    private List<Quote> quotes;
    private List<QuoteRole> quoteRoles;
    private List<RateAmount> rateAmounts;
    private List<ReorderGuideline> reorderGuidelines;
    private List<RequirementRole> requirementRoles;
    private List<RespondingParty> respondingParties;
    private List<ReturnHeader> returnHeaders1;
    private List<ReturnHeader> returnHeaders2;
    private List<SalesForecast> salesForecasts1;
    private List<SalesForecast> salesForecasts2;
    private List<SalesForecastHistory> salesForecastHistories1;
    private List<SalesForecastHistory> salesForecastHistories2;
    private List<SalesOpportunityRole> salesOpportunityRoles;
    private List<Shipment> shipments1;
    private List<Shipment> shipments2;
    private List<ShipmentCostEstimate> shipmentCostEstimates;
    private List<ShipmentReceiptRole> shipmentReceiptRoles;
    private List<ShipmentRouteSegment> shipmentRouteSegments;
    private List<ShoppingList> shoppingLists;
    private List<Subscription> subscriptions1;
    private List<Subscription> subscriptions2;
    private List<SupplierProduct> supplierProducts;
    private List<SupplierProductFeature> supplierProductFeatures;
    private List<TaxAuthority> taxAuthorities;
    private List<TaxAuthorityGlAccount> taxAuthorityGlAccounts;
    private List<Timesheet> timesheets1;
    private List<Timesheet> timesheets2;
    private List<TimesheetRole> timesheetRoles;
    private List<TimeEntry> timeEntries;
    private List<UserLogin> userLogins;
    private List<UserLoginHistory> userLoginHistories;
    private List<VarianceReasonGlAccount> varianceReasonGlAccounts;
    private Vendor vendor;
    private List<VendorProduct> vendorProducts;
    private List<WebUserPreference> webUserPreferences;
    private List<WorkEffortEventReminder> workEffortEventReminders;*/
}