package com.bizoffs.order.pojo;

import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

;

@Data
public class WorkEffort implements Serializable {
    private static final long serialVersionUID = 1L;
    private String workEffortId;
    private String accommodationMapId;
    private String accommodationSpotId;
    private Timestamp actualCompletionDate;
    private double actualMilliSeconds;
    private double actualSetupMillis;
    private Timestamp actualStartDate;
    private String createdByUserLogin;
    private Timestamp createdDate;
    private Timestamp createdStamp;
    private Timestamp createdTxStamp;
    private String currentStatusId;
    private String description;
    private String estimateCalcMethod;
    private Timestamp estimatedCompletionDate;
    private double estimatedMilliSeconds;
    private double estimatedSetupMillis;
    private Timestamp estimatedStartDate;
    private String facilityId;
    private String fixedAssetId;
    private String infoUrl;
    private String lastModifiedByUserLogin;
    private Timestamp lastModifiedDate;
    private Timestamp lastStatusUpdate;
    private Timestamp lastUpdatedStamp;
    private Timestamp lastUpdatedTxStamp;
    private String locationDesc;
    private String moneyUomId;
    private String noteId;
    private BigDecimal percentComplete;
    private Long priority;
    private BigDecimal quantityProduced;
    private BigDecimal quantityRejected;
    private BigDecimal quantityToProduce;
    private String recurrenceInfoId;
    private BigDecimal reservNthPPPerc;
    private BigDecimal reservPersons;
    private BigDecimal reserv2ndPPPerc;
    private BigDecimal revisionNumber;
    private String runtimeDataId;
    private String scopeEnumId;
    private String sendNotificationEmail;
    private String serviceLoaderName;
    private String showAsEnumId;
    private String sourceReferenceId;
    private String specialTerms;
    private String tempExprId;
    private BigDecimal timeTransparency;
    private double totalMilliSecondsAllowed;
    private BigDecimal totalMoneyAllowed;
    private String universalId;
    private String workEffortName;
    /*private Uom uom;
    private TemporalExpression temporalExpression;
    private StatusItem statusItem;
    private RecurrenceInfo recurrenceInfo;
    private WorkEffort workEffort;
    private List<WorkEffort> workEfforts;
    private WorkEffortPurposeType workEffortPurposeType;
    private WorkEffortType workEffortType;
    private List<WorkEffortAssoc> workEffortAssocs1;
    private List<WorkEffortAssoc> workEffortAssocs2;
    private List<WorkEffortAttribute> workEffortAttributes;
    private RuntimeData runtimeData;
    private List<WorkEffortBilling> workEffortBillings;
    private List<WorkEffortContactMechNew> workEffortContactMechNews;
    private List<WorkEffortContent> workEffortContents;
    private List<WorkEffortCostCalc> workEffortCostCalcs;
    private List<WorkEffortDeliverableProd> workEffortDeliverableProds;
    private List<WorkEffortEventReminder> workEffortEventReminders;
    private List<WorkEffortFixedAssetAssign> workEffortFixedAssetAssigns;
    private List<WorkEffortFixedAssetStd> workEffortFixedAssetStds;
    private List<WorkEffortGoodStandard> workEffortGoodStandards;
    private WorkEffortIcalData workEffortIcalData;
    private List<WorkEffortInventoryAssign> workEffortInventoryAssigns;
    private List<WorkEffortInventoryProduced> workEffortInventoryProduceds;
    private List<WorkEffortKeyword> workEffortKeywords;
    private List<WorkEffortNote> workEffortNotes;
    private List<WorkEffortPartyAssignment> workEffortPartyAssignments;
    private List<WorkEffortReview> workEffortReviews;
    private List<WorkEffortSkillStandard> workEffortSkillStandards;
    private List<WorkEffortStatus> workEffortStatuses;
    private NoteData noteData;
    private List<WorkEffortSurveyAppl> workEffortSurveyAppls;
    private List<WorkEffortTransBox> workEffortTransBoxs;
    private List<WorkOrderItemFulfillment> workOrderItemFulfillments;
    private List<WorkRequirementFulfillment> workRequirementFulfillments;
    private Facility facility;
    private AccommodationMap accommodationMap;
    private AccommodationSpot accommodationSpot;
    private CustomMethod customMethod;
    private Enumeration enumeration;
    private FixedAsset fixedAsset;*/
}